config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  #get 'projects/index'
  get "/projects", to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out', :to => 'active_admin/devise/sessions#destroy'
  end
  ActiveAdmin.routes(self)
  root to: "projects#index"
  resources :projects do
    resources :tasks do
      get 'change_status', on: :member
    end
  end

end

app/models/task.rb
class Task < ApplicationRecord
  #include AASM

  belongs_to :project
  belongs_to :user

  has_one_attached :image

  # validate :image_type
  validates :title, presence: true
  #validates :user_id, presence: true

  belongs_to :creator, class_name: "User"

  # aasm do
  #   state :started, initial: true
  #   state :in_progress
  #   state :completed
  #   state :resolved

  #   event :next do
  #     transitions from: :started, to: :in_progress
  #     transitions from: :in_progress, to: :completed

  #   end

  #   event :clean do
  #     transitions from: :running, to: :cleaning
  #   end

  #   event :sleep do
  #     transitions from: [:running, :cleaning], to: :sleeping
  #   end
  # end

private

def image_type
   if image.attached? == false
     errors.add(:image, "is missing!")
   elsif !image.content_type.in?(%('image/jpeg image/png'))
     errors.add(:image, "needs to be a jpeg or png!")
   end
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy, :change_status]
  before_action :authenticate_user!
  def new
    #debugger
    @project = Project.find(params[:project_id])
  end

  def create
    # @project = Project.find(params[:project_id])
    #  @task = @project.tasks.create(task_params)
    #  redirect_to project_path(@project)
    #debugger
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.creator_id = current_user.id

    if @task.save
      redirect_to project_path(@project), notice: "Task created successfully."
    else
      @task.errors.messages[:image].first
      flash.now[:notice] = "Task creation failed"
      render :new
    end
  end

  def change_status
    #debugger
    @task = Task.find(params[:id])
    if @task.aasm.fire!(params[:name])
      redirect_to request.referer, notice: "Status changed successfully."
    else
      redirect_to request.referer, notice: "Status changed failed"
    end
  end

  def show
    @project = Project.find(params[:project_id])
  end

  def edit

  end

  def update
    if  @project.update(task_params)
      redirect_to @task
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  # def find_project
  #   @project = Project.find(params[:project_id])
  # end

  def task_params
    params.require(:task).permit(:title, :description, :user_id, :status,:type, :image)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/new.html.erb
<h4>Add Task</h4>

<div class="container">
  <%= simple_form_for [@project, @project.tasks.new] do |f| %>

    <%= f.input :title, input_html: {class: "w-25"} %>
    <%= f.input :description, input_html: {class: "w-25"} %>
    <div class="mx-1 my-1">
      <%= label :selectUser, 'Select user' %>
      <%= f.select :user_id, @project.users.all.collect { |u| [u.name, u.id]}, {:include_blank => true, include_hidden: false}  %>
    </div>

    <div class="mx-1 my-1">
      <%= f.collection_radio_buttons :type, [['Feature', 'Feature'] ,['Bug', 'Bug']],:first, :last %>
    </div>
    <div class="mx-1 my-1">
      <%= f.file_field :image%>
    </div>
    <div class="mx-1 my-2">
      <%= f.button :submit, class:"btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2>Task Details</h2>
  <div class="row text-center fw-bold fs-2">
    <p><%= @task.title %></p>
  </div>
  <h3>Description: </h3>
  <div class="ms-5 fs-2"> <%= @task.description %></div>
  <div class="row">
    <p class="fw-normal fs-3">Assign User: <span class="ms-3 fs-4"><%= @task.user.name %></span>
      <span class="fs-4">{<%= @task.user.roles.pluck(:name).first %>}</span></p>
  </div>
  <div class="row">
    <p class="fw-normal fs-3">Task Type: <span class="ms-3 fs-4"><%= @task.type %></span></p>
  </div>
  <div class="row">
    <p class="fw-normal fs-3">Task Status: <span class="ms-3 fs-4"><%= @task.aasm_state %></span></p>
  </div>
  <div class="dropdown">
    <a class="btn btn-outline-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
      Change Status
    </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% @task.aasm.events.map(&:name).each  do |event|%>
          <li class="dropdown-item">
            <%= link_to "#{event}", change_status_project_task_path(name: "#{event}") %>
          </li>
        <% end %>
      </ul>
  </div>
  <% if @task.image.attached? %>
    <h3>Screenshot: </h3>
    <div class="ms-5">
      <%= image_tag(@task.image, class: "w-50") %>
    </div>
  <% end %>


  <div class="text-center mb-4 mt-4">
    <% if policy(@project).edit? %>
      <%= link_to "Edit Project", edit_project_path(@project), :class => "btn btn-outline-info btn-sm" %>
      <%= link_to "Delete Project", project_path(@project), :class => "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are your sure?"} %>
    <% end %>
    <%= link_to "Add Task", new_project_task_path(@project), :class => "btn btn-outline-primary btn-sm" %>
  </div>
</div>