config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  #get 'projects/index'
  get "/projects", to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out', :to => 'active_admin/devise/sessions#destroy'
  end
  ActiveAdmin.routes(self)
  root to: "projects#index"
  resources :projects do
    resources :tasks do
      get 'change_status', on: :member
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users, dependent: :destroy
  has_many :tasks, dependent: :destroy

  belongs_to :creator, class_name: "User"

  validates :title, presence: true
  # belongs_to :customer
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if
      @projects = policy_scope(Project)
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    debugger
    @project = Project.new(project_params)
    @project.creator_id = current_user.id
    if @project.save
      redirect_to projects_path, notice: "Project created successfully."
    else
      render 'new'
    end
  end

  def show
    #authorize @project
  end


  def edit
    authorize @project
  end

  def update
    debugger
    #@project = Project.update(project_params)
    #@project.creator_id = current_user.id
    if @project.update(project_params)
      redirect_to @project, notice: "Project updated successfully."
    else
      render 'edit'
    end

  end

  def destroy
    #debugger
    authorize @project
    if @project.destroy
      redirect_to root_path, notice: "Project deleted successfully"
    else
      redirect_to @project, notice: "Deletion Failed"
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, user_ids: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="container">
  <h2>Edit Project</h2>
</div>

<div class="container">
  <%= simple_form_for @project do |f| %>

    <%= f.input :title, input_html: {class: "w-25"} %>
    <%= f.input :description, input_html: {class: "w-25"} %>
    <%= f.select :user_ids, User.all.collect { |u| [u.name, u.id]}, {:include_blank => false, include_hidden: false}, :multiple => true %>
    <!-- <%= f.association :users, :collection => User.all, :input_html => { :multiple => true }  %> -->
    <!-- <%= f.association :users, label_method: :name, value_method: :id, include_blank: false, :input_html => {:maxlength =>50, :style=> 'width: 500px'} %> -->
    <br>
    <%= f.button :submit, class:"btn-primary" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<% viewer = current_user.present? ? current_user.name : 'Stranger' %>



<div class="container">
  <h2 class="text-primary">Hello <%= viewer %>, Welcome to testProject</h2>
  <h2>Projects#index</h2>
  <p>Find me in app/views/projects/index.html.erb</p>
</div>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td> <%= link_to "Show", project, :class => "btn btn-outline-info btn-sm" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h3 class="text-center">Add Project</h3>

<div class="container ms-auto">
  <%= simple_form_for @project do |f| %>

    <%= f.input :title, input_html: {class: "w-25"} %>
    <%= f.input :description, input_html: {class: "w-25"} %>
    <div class="mx-1">
      <%= label :selectUsers, 'Select Team:' %>
    </div>
    <div class="mx-3 my-2">
      <%= f.select :user_ids, User.all.collect { |u| [u.name, u.id]}, {:include_blank => false, include_hidden: false}, :multiple => true  %>
    </div>
    <!-- <%= f.association :users, :collection => User.all, :input_html => { :multiple => true }  %> -->
    <!-- <%= f.association :users, label_method: :name, value_method: :id, include_blank: false, :input_html => {:maxlength =>50, :style=> 'width: 500px'} %> -->

    <%= f.button :submit, class:"btn-primary" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container">
      <h2>Project Details</h2>
      <div class="row text-center">
        <h3><%= @project.title %></h3>
      </div>
      <h4>Description: </h4>
      <div class="ms-5 fs-2"> <%= @project.description %></div>
      <h4>Assign Users:</h4>
      <div class="d-flex justify-content-center">
        <table class="table table-striped w-75">
          <thead>
            <tr>
              <th>User Name</th>
              <th>Role</th>
            </tr>
          </thead>
          <tbody>
            <% @project.users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.roles.pluck(:name).first %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="text-center">
        <% if policy(@project).edit? %>
          <%= link_to "Edit Project", edit_project_path(@project), :class => "btn btn-outline-info btn-sm" %>
          <%= link_to "Delete Project", project_path(@project), :class => "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are your sure?"} %>
        <% end %>
        <%= link_to "Add Task", new_project_task_path(@project), :class => "btn btn-outline-primary btn-sm" %>
      </div>
</div>
<hr>

<div class="container">
  <h3>Task List</h3>
  <div class="d-flex justify-content-center">
    <table class="table table-striped w-75">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Task Type</th>
          <th>Developer</th>
          <th>Role</th>
          <th>Task Status</th>
          <th>Action</th>
        </tr>
      </thead>
        <tbody>
          <% @project.tasks.each_with_index do |task, idx| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.description %></td>
              <td><%= task.type %></td>
              <td><%= task.user.name %></td>
              <td><%= task.user.roles.pluck(:name).first %></td>
              <td><%= task.aasm_state %></td>
              <td> <%= link_to "Show",  project_task_url(@project, task), :class => "btn btn-outline-info btn-sm" %>
                  <%= link_to "Delete",  project_task_url(@project, task), :class => "btn btn-outline-info btn-sm" %>
                  <!-- <button type="button" class="btn btn-link btn-outline-info btn-sm"
                    data-reflex="click->ExampleReflex#delete"
                    data-id="<%= task.id %>">Delete Task</button> -->
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>